- hosts: all
  become: true
  tasks:

    - name: Add Kali source package.
      lineinfile:
        path: /etc/apt/sources.list
        line: deb http://http.kali.org/kali kali-rolling main contrib non-free
    
    - name: Getting the keys for Kali repo
      get_url:
        url: http://old.kali.org/kali/pool/main/k/kali-archive-keyring/kali-archive-keyring_2022.1_all.deb
        dest: /tmp/kali-archive-keyring_2022.1_all.deb

    - name: Installing the keys
      ansible.builtin.command: dpkg -i /tmp/kali-archive-keyring_2022.1_all.deb

    - name: Getting the XSS tool
      git:
        repo: https://github.com/pwn0sec/PwnXSS
        dest: /opt/attack/PwnXSS
        clone: yes
        force: true
        update: yes

    - name: Update package manager cache
      apt:
        update_cache: true

    - name: Install our tools
      apt:
        name: 
          - sqlmap
          - dirbuster
          - nmap
        state: present

    - name: Create a directory for the attack script
      file:
        path: /opt/attack
        state: directory
        mode: 0755
        owner: root
        group: root

    - name: Create a directory with venv
      file:
        path: /opt/attack/venv
        state: directory
        mode: 0755
        owner: root
        group: root

    - name: Copying the attack script to the remote host
      copy:
        src: /home/kali/Attack-defense-automation/src/attack/attack.py
        dest: /opt/attack

    - name: Installing venv
      pip:
        name: virtualenv

    - name: Copying the requirements
      copy:
        src: /home/kali/Attack-defense-automation/src/attack/requirements.txt
        dest: /opt/attack/requirements.txt

    - name: Setting up the venv
      pip:
        requirements: /opt/attack/requirements.txt
        virtualenv: /opt/attack/venv
        virtualenv_python: python3
    - name: Launching the attack script
      command: sudo python3 /opt/attack/attack.py
      register: command_output

    - debug:
        var: command_output.stdout_lines