---
- hosts: all
  become: true

  tasks:
    - name: Update package manager cache
      apt:
        update_cache: true

    - name: Install Apache web server
      apt:
        name: apache2
        state: present

    - name: Install PHP
      apt:
        name: php
        state: present

    - name: Download Mutillidae
      get_url:
        url: "https://sourceforge.net/projects/mutillidae/files/latest/download"
        dest: "/var/www/html/mutillidae.zip"

    - name: Unzip Mutillidae
      unarchive:
        src: "/var/www/html/mutillidae.zip"
        dest: "/var/www/html"
        remote_src: true

    - name: Set permissions for Mutillidae files
      file:
        path: "/var/www/html/mutillidae"
        owner: "www-data"
        group: "www-data"
        mode: "u+rwx,g+rwx,o+rwx"
        state: directory
        recurse: true

    - name: Enable Apache service
      service:
        name: apache2
        enabled: true

    - name: Start Apache service
      service:
        name: apache2
        state: started

    - name: Install Python libraries
      pip:
        name:
          - http.server
          - re
        state: present

#    - name: Copy Python script
#      copy:
#        src: "attack_handler.py"
#        dest: "/var/www/html/attack_handler.py"

#    - name: Run Python script
#      command: "python /var/www/html/attack_handler.py"
#      async: 7200
#      poll: 0
